# Generated by Django 4.1 on 2022-08-04 11:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('email', models.EmailField(error_messages={'error': 'Bunday email mavjud.'}, max_length=254, null=True, unique=True, verbose_name='email')),
                ('bio', models.CharField(blank=True, max_length=256, null=True)),
                ('awatar', models.ImageField(blank=True, null=True, upload_to='awatar/')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='bg_image/')),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('linkedln', models.CharField(blank=True, max_length=256, null=True)),
                ('flowwing_count', models.PositiveIntegerField(blank=True, null=True)),
                ('followers_count', models.PositiveIntegerField(blank=True, null=True)),
                ('blocked_users_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('blocked_users', models.ManyToManyField(blank=True, null=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
                ('flowwing', models.ManyToManyField(blank=True, null=True, related_name='user_following', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='user_follower', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
