# Generated by Django 4.1 on 2022-08-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_worker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='awatar',
        ),
    ]
